In [101]:
!pip uninstall jedi

^C


## 2. 넘파이로 텐서 민들기 (벡터와 행렬 만들기)

In [1]:
import numpy as np

### 1) 1D with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print(f'Rank of t: {t.ndim}') # 몇 차원인지 출력
print(f'Shape of t: {t.shape}') # 텐서의 크기를 출력

Rank of t: 1
Shape of t: (7,)


#### 1-1) Numpy 기초

In [10]:
print(f't[0] t[1] t[-1]= {t[0]}, {t[1]}, {t[-1]}')

t[0] t[1] t[-1]= 0.0, 1.0, 6.0


In [12]:
print(f't[2:5], t[4:-1] = {t[2:5]} {t[4:-1]}')

t[2:5], t[4:-1] = [2. 3. 4.] [4. 5.]


In [13]:
print(f't[:2] t[3:] = {t[:2]} {t[3:]}')

t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]


### 2) 2D with Numpy

In [14]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [15]:
print(f'Rank of t: {t.ndim}') # 몇 차원인지 출력
print(f'Shape of t: {t.shape}') # 텐서의 크기를 출력

Rank of t: 2
Shape of t: (4, 3)


## 3. 파이토치 텐서 선언하기

In [17]:
!pip install torch

   ---------------------------------------- 0.0/198.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/198.6 MB 2.4 MB/s eta 0:01:23
   ---------------------------------------- 0.3/198.6 MB 3.3 MB/s eta 0:01:01
   ---------------------------------------- 0.6/198.6 MB 4.4 MB/s eta 0:00:46
   ---------------------------------------- 1.1/198.6 MB 6.2 MB/s eta 0:00:32
   ---------------------------------------- 1.5/198.6 MB 6.7 MB/s eta 0:00:30
   ---------------------------------------- 2.0/198.6 MB 7.5 MB/s eta 0:00:27
    --------------------------------------- 2.7/198.6 MB 8.7 MB/s eta 0:00:23
    --------------------------------------- 3.2/198.6 MB 8.8 MB/s eta 0:00:23
    --------------------------------------- 3.8/198.6 MB 9.4 MB/s eta 0:00:21
    --------------------------------------- 4.6/198.6 MB 10.2 MB/s eta 0:00:20
   - -------------------------------------- 5.3/198.6 MB 10.5 MB/s eta 0:00:19
   - -------------------------------------- 6.0/198.6 MB 11.0 MB/s et

In [18]:
import torch

### 1) 1D with Pytorch

In [19]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [20]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [21]:
print(t[0], t[1], t[2])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(2.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2) 2D with Pytorxh

In [26]:
t= torch.FloatTensor([[1., 2., 3.], 
                     [4., 5., 6.],
                     [7., 8., 9.],
                     [10., 11., 12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [27]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [31]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])



### 3) boadcasing

In [32]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1+m2)

tensor([[5., 5.]])


In [35]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [36]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


### 4) 자주 사용되는 기능들

#### (1) 행렬 곱과 원소 곱

In [39]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1:', m1.shape)
print('Shape of Matrix 2:', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [40]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1:', m1.shape)
print('Shape of Matrix 2:', m2.shape)
print(m1.mul(m2))

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])


#### (2) mean

In [41]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [43]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


In [46]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean(dim=0)) # 각 열의 평균값을 구한다 dim=0이라는 것은 t의 첫번째 차원을 제거

tensor([2., 3.])


In [47]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


#### (3) sum

In [48]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [50]:
print(t.sum()) # 전체 원소의 덧셈
print(t.sum(dim=0)) # 행을 제거 -> 첫 번째 차원이 바뀌는 위치만 더하면 됨 (0, 0) + (0, 1)
print(t.sum(dim=1)) # 열을 제거 -> (0, 0) + (1, 0)
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### (4) max, argmax

In [51]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [52]:
print(t.max())

tensor(4.)


In [53]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [54]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [55]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


#### (5) view

In [59]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)

print(ft)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [60]:
print(ft.view(-1, 3))
print(ft.view(-1, 3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [61]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### (6) squeeze

In [62]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [64]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#### (7) unsqueeze

In [65]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [66]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [67]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [68]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [69]:
print(ft.unsqueeze(-1)) # 마지막 차원에 1인 차원을 추가
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### (8) type casting

In [70]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [71]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [74]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [76]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


#### (9) concatenate

In [79]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [80]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [78]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#### (10) STACKING

In [81]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [82]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [87]:
print(torch.cat([x, y, z]))

tensor([1., 4., 2., 5., 3., 6.])


In [90]:
print(x.unsqueeze(0)) # 0번째에 차원 1개를 추가한다.

tensor([[1., 4.]])


In [91]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [93]:
print(torch.stack([x, y, z], dim=1)) # 열을 따라서 스택을 쌓는다

tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### (11) ones_like와 zeros_like

In [94]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [95]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [96]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### (12) In-place Operation (덮어쓰기 연산)

In [98]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [99]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [100]:
print(x.mul_(2.)) # 연산 뒤에 _ 을 붙이면 기존 값에 덮어쓴다
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## 4. 파이썬 클래스

## 1) 함수와 클래스의 차이

In [103]:
result = 0

In [104]:
def add(num):
    global result
    result += num
    return result

In [105]:
print(add(3))
print(add(4))

3
7


In [106]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))


3
7
3
10


In [108]:
class Calculator:
    def __init__(self):
        self.result = 0
    def add(self, num):
        self.result += num
        return self.result

In [109]:
cal1=Calculator()

In [110]:
cal2=Calculator()

In [111]:
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))


3
7
3
10
